In [118]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import nltk
import csv
nltk.download('punkt')
from math import log
from operator import itemgetter

[nltk_data] Downloading package punkt to C:\Users\Rijal
[nltk_data]     Muslim\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [98]:
# Import Library Sklearn
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer


# Import Library untuk Stemming
!pip install Sastrawi
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory

Requirement already satisfied: Sastrawi in c:\users\rijal muslim\anaconda3\lib\site-packages (1.0.1)

In [99]:
# Read Dataset
df = pd.read_csv('dataset.csv')
df = df.drop('Unnamed: 1', 1)
df

,Judul,Abstract
0,SISTEM TEMU KEMBALI INFORMASI PADA DOKUMEN DEN...,Informasi saat ini sangat mudah didapatkan den...
1,PENERAPAN SISTEM TEMU KEMBALI INFORMASI PADA\n...,Sistem temu kembali informasi (information ret...
2,RELEVANCE FEEDBACK PADA TEMU-KEMBALI TEKS \n B...,Tujuan penelitian ini adalah mengimplementasik...
3,IMPLEMENTASI INFORMATION RETRIVALS UNTUK MENIN...,—Brosur marketing adalah alat yang digunakan o...
4,IMPLEMENTASI VECTOR SPACE MODEL PADA SISTEM\n ...,Semakin berkembangnya bisnis karaoke sekarang ...
5,Pemanfaatan Metode Vector Space Model dan\n Me...,Hama dan penyakit yang menyerang tanaman padi ...

In [100]:
# Ukuran Dataset
print('Ukuran dataset:', df.shape)

Ukuran dataset: (6, 2)

In [101]:
# Pembagian data training & testing
x_train, x_test, y_train, y_test = train_test_split(df['Judul'], df['Abstract'], train_size=0.5, test_size=0.16)

In [102]:
train_data = pd.DataFrame({'Judul':x_train, 'Abstract':y_train})
test_data = pd.DataFrame({'Judul':x_test, 'Abstract':y_test})

In [103]:
train_data.head()

,Judul,Abstract
0,SISTEM TEMU KEMBALI INFORMASI PADA DOKUMEN DEN...,Informasi saat ini sangat mudah didapatkan den...
1,PENERAPAN SISTEM TEMU KEMBALI INFORMASI PADA\n...,Sistem temu kembali informasi (information ret...
3,IMPLEMENTASI INFORMATION RETRIVALS UNTUK MENIN...,—Brosur marketing adalah alat yang digunakan o...

In [104]:
test_data.head()

,Judul,Abstract
2,RELEVANCE FEEDBACK PADA TEMU-KEMBALI TEKS \n B...,Tujuan penelitian ini adalah mengimplementasik...

In [105]:
# Ukuran Data Training & Testing
print('Ukuran data train:', train_data.shape)
print('Ukuran data test:', test_data.shape)
n_train = train_data.shape[0]
n_test = test_data.shape[0]

Ukuran data train: (3, 2)
Ukuran data test: (1, 2)

In [106]:
sparse_data = pd.concat([train_data, test_data], ignore_index=True)
sparse_data.head()

,Judul,Abstract
0,SISTEM TEMU KEMBALI INFORMASI PADA DOKUMEN DEN...,Informasi saat ini sangat mudah didapatkan den...
1,PENERAPAN SISTEM TEMU KEMBALI INFORMASI PADA\n...,Sistem temu kembali informasi (information ret...
2,IMPLEMENTASI INFORMATION RETRIVALS UNTUK MENIN...,—Brosur marketing adalah alat yang digunakan o...
3,RELEVANCE FEEDBACK PADA TEMU-KEMBALI TEKS \n B...,Tujuan penelitian ini adalah mengimplementasik...

In [107]:
# Ukuran Sparse Data
print('Ukuran sparse data:', sparse_data.shape)
n_document = sparse_data.shape[0]

Ukuran sparse data: (4, 2)

In [108]:
vectorizer = CountVectorizer()
tf = vectorizer.fit_transform(sparse_data['Abstract'])
print('Jumlah dokumen:', tf.shape[0])
print('Jumlah term:', tf.shape[1])

Jumlah dokumen: 4
Jumlah term: 301

In [109]:
print('Daftar Term:')
vectorizer.get_feature_names()

Daftar Term:

['14',
 '15',
 '2002',
 '2003',
 '30',
 '44',
 '447',
 '500',
 '512',
 '516',
 '54',
 'ada',
 'adalah',
 'akan',
 'alat',
 'algoritma',
 'and',
 'artikel',
 'atas',
 'atau',
 'awal',
 'awalnya',
 'bahasa',
 'bahwa',
 'banyaknya',
 'based',
 'bayes',
 'beberapa',
 'begitu',
 'berbagai',
 'berbahasa',
 'berbasis',
 'berdasarkan',
 'berjumlah',
 'berkaitan',
 'berupa',
 'besar',
 'bisa',
 'bobot',
 'brosur',
 'buruk',
 'by',
 'cara',
 'cepat',
 'cocok',
 'control',
 'corpus',
 'cosine',
 'cukup',
 'dalam',
 'dan',
 'dapat',
 'dari',
 'dasar',
 'data',
 'dec',
 'dengan',
 'developer',
 'di',
 'dibeberapa',
 'dibuktikan',
 'dibutuhkan',
 'dicari',
 'didapat',
 'didapatkan',
 'digunakan',
 'dihadapi',
 'diharapkan',
 'diindeks',
 'diinginkan',
 'dikenal',
 'diklasifikasi',
 'dilakukan',
 'dimanapun',
 'dipengaruhi',
 'diperiksa',
 'diperlukan',
 'diperoleh',
 'disertai',
 'disimpulkan',
 'diurutkan',
 'diusulkan',
 'document',
 'dokumen',
 'dua',
 'efektif',
 'elemen',
 'engine',
 'evaluasi',
 'fasilitas',
 'feeback',
 'feedback',
 'formula',
 'frekuensi',
 'frequency',
 'frequncy',
 'group',
 'gugus',
 'hal',
 'hasil',
 'hi',
 'ide',
 'ideregular',
 'idf',
 'ilmu',
 'index',
 'indexing',
 'indonesia',
 'informasi',
 'information',
 'ini',
 'internet',
 'inverse',
 'inverted',
 'iterasi',
 'itu',
 'jawabannya',
 'juga',
 'jumlah',
 'kapanpun',
 'karawang',
 'karena',
 'kata',
 'kebutuhan',
 'kembali',
 'kemiripan',
 'kemunculan',
 'kendala',
 'kepentingan',
 'keseluruhan',
 'kesempatan',
 'ketika',
 'kinerja',
 'koleksi',
 'komputer',
 'konsep',
 'konsepvector',
 'kota',
 'kueri',
 'kunci',
 'lain',
 'lalmas',
 'lima',
 'lingkup',
 'maka',
 'mana',
 'marketing',
 'masing',
 'massa',
 'materil',
 'media',
 'melakukan',
 'melengkapi',
 'melihat',
 'memakai',
 'memanfaatkan',
 'memang',
 'membangun',
 'membantu',
 'memberikan',
 'memenuhi',
 'memiliki',
 'memuaskan',
 'memudahkan',
 'menawarkan',
 'mencapai',
 'mencari',
 'mendapatkan',
 'mendasar',
 'menemukan',
 'menerapkan',
 'menganalisis',
 'mengelompokkan',
 'mengembangkan',
 'menggunakan',
 'menghitung',
 'mengimplementasikan',
 'meningkat',
 'meningkatkan',
 'menjadi',
 'menjanjikan',
 'menunjukkan',
 'menyaring',
 'menyebabkan',
 'menyimpan',
 'merupakan',
 'mesin',
 'metode',
 'model',
 'modeldengan',
 'mudah',
 'namun',
 'naïve',
 'nilai',
 'observasi',
 'oleh',
 'online',
 'otomatis',
 'pada',
 'peluang',
 'pemanfaatan',
 'pembobotan',
 'pembobotannya',
 'pemilihan',
 'pencapaian',
 'pencarian',
 'penelitian',
 'pengguna',
 'penggunaan',
 'penggunanya',
 'pengindeksan',
 'pengujian',
 'peningkatan',
 'penjualan',
 'penting',
 'penyimpanan',
 'perbandingan',
 'perhitungan',
 'perlu',
 'perluasan',
 'permasalahan',
 'pertama',
 'pertanian',
 'perumahan',
 'produk',
 'produknya',
 'proses',
 'prosesretrieval',
 'query',
 'regular',
 'relevan',
 'relevance',
 'retrieval',
 'retrivals',
 'ridha',
 'rocchio',
 'ruang',
 'rule',
 'ruthven',
 'saat',
 'salah',
 'sangat',
 'satu',
 'search',
 'sebaliknya',
 'sebuah',
 'secara',
 'sedangkan',
 'sehingga',
 'sejauh',
 'sekaligus',
 'sekumpulan',
 'sementara',
 'semua',
 'sendiri',
 'seorang',
 'sepuluh',
 'sesuai',
 'siklus',
 'similarity',
 'sisi',
 'sistem',
 'situs',
 'skripsi',
 'solusi',
 'space',
 'stemming',
 'stoplist',
 'suatu',
 'sudah',
 'system',
 'tanpa',
 'target',
 'telah',
 'temu',
 'tepat',
 'terbesar',
 'terdapat',
 'terdiri',
 'terhadap',
 'terlalu',
 'term',
 'terpaksa',
 'tersebut',
 'tersedia',
 'tersimpan',
 'test',
 'tf',
 'tiap',
 'tidak',
 'tinggi',
 'tujuan',
 'untuk',
 'utama',
 'variasi',
 'vector',
 'vektor',
 'vsm',
 'yaitu',
 'yakni',
 'yang']

In [110]:
vectorizer = CountVectorizer()
tf = vectorizer.fit_transform(sparse_data['Abstract'])
print('Jumlah dokumen:', tf.shape[0])
print('Jumlah term:', tf.shape[1])

Jumlah dokumen: 4
Jumlah term: 301

In [111]:
print('Matriks Tf:')
tf_matrix = pd.DataFrame(tf.toarray(), columns=vectorizer.get_feature_names())
tf_matrix

Matriks Tf:

,14,15,2002,2003,30,44,447,500,512,516,...,tujuan,untuk,utama,variasi,vector,vektor,vsm,yaitu,yakni,yang
0,0,0,0,0,0,0,0,0,0,0,...,0,3,0,0,3,0,2,0,0,11
1,0,0,0,0,0,0,0,0,0,0,...,1,5,1,0,1,0,0,1,0,3
2,0,0,0,0,0,0,0,0,0,0,...,0,3,0,0,3,2,0,0,0,13
3,1,1,1,1,1,1,1,1,1,1,...,1,5,0,1,1,0,0,0,1,9